README.md
Could I also get permissions to this repo @shannona
=> Update Readme title to The Hague

advance-readings/README.md
Add instructions for RWOT11 discount code
=> Add instructions for RWOT11 discount code 

README.md
Add link to EventBrite tickets
=> Add link to EventBrite tickets

advance-readings/README.md, advance-readings/eSSIF-Lab - Towards a European SSI ecosystem.md
Add eSSIF-Lab paper and metadata
=> Add eSSIF-Lab paper and metadata

README.md, advance-readings/CESR-adapter-for-sophisticated-multisig.md, advance-readings/README.md
Hi Shanon,
The PR also contains the correction of a broken link in your root README.md.
Best, Henk
=> advance-readings submission CESR-adapter-for-sophisticated-multisig Henk van Cann

advance-readings/eSSIF-Lab - Towards a European SSI ecosystem.md
I added the Gimly project directly into the Essif-lab ecosystem paper proposal
=> Added Gimly SSI-NFC project in Essif-lab ecosystem paper

advance-readings/README.md, advance-readings/did-resources.md
- 50% for the "just did it" quote
- 50% to find out if DIDs can be used for more
=> Add did-resources 

advance-readings/eSSIF-Lab - Towards a European SSI ecosystem.md
=> Update eSSIF-Lab - Towards a European SSI ecosystem.md

advance-readings/README.md
=> Add alphabetical link for Rendering Verifiable Credentials

advance-readings/README.md, advance-readings/data-generator.md
Signed-off-by: Moriarty <moritz@animo.id>
=> docs: paper proposal for data generator.

advance-readings/README.md
=> Reordering alphabetically

advance-readings/README.md, advance-readings/advanced-didcomm-messaging.md
Signed-off-by: Karim Stekelenburg <karim@animo.id>
=> feat: add Advanced DIDComm Messaging proposal

advance-readings/README.md, advance-readings/identity-bridge.md
Leverage the power of national European identities to obtain SSI credentials, starting from the Italian SPID ecosystem!
=> Add Identity Bridge advanced reading

advance-readings/README.md, advance-readings/csr.md
Submission for Advance Readings; we're all set already on ticket codes, so no worries there.
=> Bc csr paper

advance-readings/authentication-and-authorization-using-verifiable-credentials.md
This pull request fixes some typos. Additionally, it adds a new `Acknowledgment` section.
=> some typos fixed, ack to essif-lab and aueb-rc added

advance-readings/README.md, advance-readings/authorized-issuer-lists.md
This PR adds the AuthorizedIssuerList Verifiable Credential proposal to the repository.
=> Add AuthorizedIssuerList Verifiable Credential.

advance-readings/README.md, advance-readings/enhancing-didcomm-for-mobile-environments.md
Advance reading proposal for RWOT11
Signed-off-by: Ariel Gentile <gentilester@gmail.com>
=> Add Enhancing DIDComm messaging for mobile environments

advance-readings/README.md, advance-readings/anoncreds-ledger-agnostic-spec.md
Signed-off-by: Stephen Curran <swcurran@gmail.com>
=> Proposal for an RWoT Paper on the AnonCreds Specification and Implementations

advance-readings/Identity and Trust in a Co-operative Ecosystem.md
Updated and added references to other work.
=> References and additional context added to previous version

advance-readings/README.md, advance-readings/on-chain-dids.md
Advanced Reading Submission by Martin Riedel, Identity.com for RWOT11.
=> RWOT11 Submission - On-Chain DIDs

advance-readings/README.md, advance-readings/comparing-wallet-security-architectures.md
a theoretical comparison between native mobile wallet and cloud wallets and all the possible hybrid solutions inbetween
=> Comparing Wallet Security Architectures

draft-documents/verfiable-credentials-holder-binding.md
added abstract on holder binding
=> added abstract on holder binding

draft-documents/on-chain-verifications.md
for On-Chain identity verification design patterns topic.
=> feat: added on-chain verification WIP document reference

draft-documents/did-merkle.md
Messy expansion with initial examples for DID Document, VC, and VP
=> Friday draft

draft-documents/selective-correlation.md
Signed-off-by: Brent Zundel <brent.zundel@gmail.com>
=> line length changes and whitespace only
